### PR TITLE
include roc lang server in nightly

### PR DESCRIPTION
**Pull request by Anton-4**

### CODE REVIEW

**Comment by ryanb** [comment]
@rtfeldman any chance we could get this in? Would live to see `roc_ls` in nightly build.

**Review by rtfeldman — APPROVED** [review]

**Comment by ryanb** [comment]
Should we update [these docs](https://github.com/ayazhafiz/roc/blob/lang-srv/crates/lang_srv/README.md) as well? They are linked from the VS Code extension. It still say this:

> At this time, only from-source installations of the binary are supported

Not sure if these are still the official docs for using `roc_ls`.

**Comment by Anton-4** [comment]
I updated the docs in our repo in #6283.  I'll try to update the link in the VS Code extension.

**Comment by Anton-4** [comment]
https://github.com/ivan-demchenko/roc-vscode-unofficial/pull/19

**Pull request merged**
