### PR TITLE
Dev refcount seamless slice

### PR DESCRIPTION
**Pull request by brian-carroll**
Add support for reference counting seamless slices in the dev backends.

### CODE REVIEW

**Comment by brian-carroll** [comment]
List done, Str to do.

**Comment by folkertdev** [comment]
maybe this can be folded in: the `FromWasmMemory` traits also need to at least handle the possibility of seamless slices (otherwise they get a really weird capacity). I think we  corrected this for lists, but not strings yet in the perceus RC PR

**Comment by brian-carroll** [comment]
> otherwise they get a really weird capacity

Who is looking at it, and what capacity would they expect to see that would _not_ be weird?
The capacity of the underlying list?
I'm struggling to see how you'd determine that.

**Comment by brian-carroll** [comment]
`FromWasmMemory` does seem to have seamless slices for Str. It's flipping the sign on the length... but isn't that just ... not the length but some random nonsense?

**Comment by lukewilliamboswell** [comment]
@brian-carroll @folkertdev I think this is PR is related to #5163 with needs these fixes to pass CI. Adding this comment so we can track this relationship.

**Comment by brian-carroll** [comment]
Yeah thanks for the reminder, I haven't gotten around to finish this, I have had other stuff going on!

**Comment by brian-carroll** [comment]
@folkertdev @lukewilliamboswell 
Sorry I haven't had much time to work on this recently but got some time this morning.
I rebased on the latest `main` and most of the tests are passing locally, but there are a couple of failures on tests using `List Str`.
I'm not sure how much time I'll have this week. If this is holding people up and you want to move things along, feel free to add commits. `DEBUG_SETTINGS.helper_procs_ir` will be helpful.


Here's the IR for decrement on `Str` and `List Str`
```
procedure `#UserApp.#help0_Dec_InLayout(STR)` (`#Attr.#arg1`):
    let `#UserApp.last_word` : I32 = StructAtIndex 2 `#Attr.#arg1`;
    let `#UserApp.zero` : I32 = 0i64;
    let `#UserApp.is_big_str` : Int1 = lowlevel NumGte `#UserApp.last_word` `#UserApp.zero`;
    if `#UserApp.is_big_str` then
        joinpoint `#UserApp.jp_chars` `#UserApp.chars`:
            let `#UserApp.addr` : I32 = lowlevel PtrCast `#UserApp.chars`;
            let `#UserApp.ptr_size` : I32 = 4i64;
            let `#UserApp.rc_addr` : U32 = lowlevel NumSubSaturated `#UserApp.addr` `#UserApp.ptr_size`;
            let `#UserApp.rc_ptr` : Boxed([]) = lowlevel PtrCast `#UserApp.rc_addr`;
            let `#UserApp.alignment` : U32 = 4i64;
            let `#UserApp.zig_call_result` : {} = lowlevel RefCountDecDataPtr `#UserApp.chars` `#UserApp.alignment`;
            let `#UserApp.unit` : {} = Struct {};
            ret `#UserApp.unit`;
        in
        let `#UserApp.length` : I32 = StructAtIndex 1 `#Attr.#arg1`;
        let `#UserApp.is_slice` : Int1 = lowlevel NumLt `#UserApp.length` `#UserApp.zero`;
        if `#UserApp.is_slice` then
            let `#UserApp.one` : I32 = 1i64;
            let `#UserApp.slice_chars` : I32 = lowlevel NumShiftLeftBy `#UserApp.length` `#UserApp.one`;
            jump `#UserApp.jp_chars` `#UserApp.slice_chars`;
        else
            let `#UserApp.string_chars` : I32 = StructAtIndex 0 `#Attr.#arg1`;
            jump `#UserApp.jp_chars` `#UserApp.string_chars`;
    else
        let `#UserApp.unit` : {} = Struct {};
        ret `#UserApp.unit`;

procedure `#UserApp.#help1_Dec_InLayout(19)` (`#Attr.#arg1`):
    let `#UserApp.len` : I32 = lowlevel ListLen `#Attr.#arg1`;
    let `#UserApp.zero` : I32 = 0i64;
    let `#UserApp.is_empty` : Int1 = lowlevel Eq `#UserApp.len` `#UserApp.zero`;
    if `#UserApp.is_empty` then
        let `#UserApp.unit` : {} = Struct {};
        ret `#UserApp.unit`;
    else
        let `#UserApp.capacity` : I32 = StructAtIndex 2 `#Attr.#arg1`;
        let `#UserApp.is_slice` : Int1 = lowlevel NumLt `#UserApp.capacity` `#UserApp.zero`;
        joinpoint `#UserApp.jp_elements` `#UserApp.elements`:
            let `#UserApp.start` : I32 = lowlevel PtrCast `#UserApp.list_elems`;
            let `#UserApp.elem_size` : I32 = 12i64;
            let `#UserApp.list_size` : I32 = lowlevel NumMul `#UserApp.len` `#UserApp.elem_size`;
            let `#UserApp.end` : I32 = lowlevel NumAdd `#UserApp.start` `#UserApp.list_size`;
            joinpoint `#UserApp.elems_loop` `#UserApp.addr`:
                let `#UserApp.is_end` : Int1 = lowlevel NumGte `#UserApp.addr` `#UserApp.end`;
                if `#UserApp.is_end` then
                    let `#UserApp.alignment` : U32 = 4i64;
                    let `#UserApp.zig_call_result` : {} = lowlevel RefCountDecDataPtr `#UserApp.elements` `#UserApp.alignment`;
                    let `#UserApp.unit` : {} = Struct {};
                    ret `#UserApp.unit`;
                else
                    let `#UserApp.box` : Boxed(Str) = lowlevel PtrCast `#UserApp.addr`;
                    let `#UserApp.elem` : Str = Unbox `#UserApp.box`;
                    let `#UserApp.mod_elem_unit` : {} = CallByName `#UserApp.#help0_Dec_InLayout(STR)` `#UserApp.elem`;
                    let `#UserApp.next_addr` : I32 = lowlevel NumAdd `#UserApp.addr` `#UserApp.elem_size`;
                    jump `#UserApp.elems_loop` `#UserApp.next_addr`;
            in
            jump `#UserApp.elems_loop` `#UserApp.start`;
        in
        if `#UserApp.is_slice` then
            let `#UserApp.one` : I32 = 1i64;
            let `#UserApp.slice_elems` : I32 = lowlevel NumShiftLeftBy `#UserApp.capacity` `#UserApp.one`;
            jump `#UserApp.jp_elements` `#UserApp.slice_elems`;
        else
            let `#UserApp.list_elems` : Boxed(Str) = StructAtIndex 0 `#Attr.#arg1`;
            jump `#UserApp.jp_elements` `#UserApp.list_elems`;

```

**Comment by brian-carroll** [comment]
And here's the (improved) stack trace from the Wasm interpreter

```
thread 'wasm_str::str_split_small_str_big_delimiter' panicked at 'ERROR: A Wasm instruction at file offset 0x13f8 tried to access memory at 0xfffffffc but the maximum address is 0x13ffff
-------------------
func[967]  
  address  00474f
  args     
  locals   0: I32(1245168)
  stack    [I32(1245168)]
-------------------
func[962]  main
  address  0045ba
  args     
  locals   0: I32(0), 1: I32(1245120)
  stack    [I32(3)]
-------------------
func[966]  #help1_Dec_InLayout(19)
  address  00470d
  args     0: I32(1245144)
  locals   1: I32(0), 2: I32(0), 3: I32(1245204), 4: I32(0), 5: I32(5), 6: I32(0), 7: I32(1245204), 8: I32(3), 9: I32(12), 10: I32(1245204), 11: I32(1245204), 12: I32(1245240), 13: I32(0), 14: I32(1245104), 15: I32(1245204), 16: I32(0)
  stack    []
-------------------
func[965]  #help0_Dec_InLayout(STR)
  address  004661
  args     0: I32(1245104)
  locals   1: I32(1), 2: I32(2), 3: I32(0), 4: I32(1), 5: I32(-2147483647), 6: I32(1), 7: I32(0), 8: I32(4)
  stack    [I32(0)]
-------------------
func[456]  roc_builtins.utils.decref_data_ptr
  address  000c8e
  args     0: I32(2), 1: I32(4)
  locals   2: I32(-4)
  stack    []
-------------------
', crates/compiler/test_gen/src/wasm_str.rs:211:5
```

**Comment by folkertdev** [comment]
I tried working on this a bit. I got it working for strings (the capacity field stores a pointer to the refcount, not to the data.

but now I got stuck a bit on lists. it is still "segfaulting" with some invalid memory address, and I'm really not sure what's going on. I'd like to use the dev backend to debug this, but there seems to be some problem with list equality there. 

So I'll have to debug this first. 

anyway, I'm happy to keep working on this until I figure it out or you have more time and can perhaps figure out what's going on with the wasm debug info.

**Comment by brian-carroll** [comment]
> the capacity field stores a pointer to the refcount, not to the data.

Ah! In that case I'm surprised I didn't get more test failures!

Did you do that work on this branch? Do you have any commits you could push?

**Comment by folkertdev** [comment]
just did so, though the list case is still broken, both on wasm and the dev backend.

on the dev backend, we somehow try to dereference (unbox) the `0x1` pointer, and I just can't figure out why.

**Comment by folkertdev** [comment]
the fixes to equality in https://github.com/roc-lang/roc/pull/5387 are also required here. I rebased on top of that branch

**Comment by folkertdev** [comment]
finally cracked this. @brian-carroll anything against merging this?

**Review by folkertdev — APPROVED** [review]

**Comment by brian-carroll** [comment]
Nope!

**Comment by brian-carroll** [comment]
Well done, thank you for completing the work!

**Pull request merged**
