### PR TITLE
Drastically simplify examples directory

### PR DESCRIPTION
**Pull request by JanCVanB**
Suggested by @rtfeldman 

## TODO

- [x] Fix tests (especially for `examples/benchmarks/` moving to `crates/cli_testing_examples/benchmarks/`)
- [ ] Merge all `examples/cli/*-platform`s into one `examples/cli/platform`
- [ ] Merge all `examples/gui/**/*platform`s into one `examples/gui/platform`? The breakout game might need its own...

### CODE REVIEW

**Comment by JanCVanB** [comment]
@Anton-4 I need some help redirecting the benchmark tests to their new parent directory. Could you please hop on this PR for that?

**Comment by Anton-4** [comment]
Sure :)

**Comment by Anton-4** [comment]
The benchmarks have been silently failing for a while, I'm going to fix pre-existing issues in a different PR first.

**Comment by JanCVanB** [comment]
@Anton-4 can you link your fix work? Is it complete and no longer blocking this PR?

**Comment by Anton-4** [comment]
Still working on it, I hope to be done with it today.

**Comment by Anton-4** [comment]
I'm working on handling the merge conflicts.

**Comment by JanCVanB** [comment]
@Anton-4 I want to get this PR merged this week, in preparation for Roctoberfest. I'm available in the next few hours to live code it with you, if you're available!

**Comment by JanCVanB** [comment]
Let me know when/if the remaining work/fixes moves into the same scope of work/knowledge as my commits, and I'm happy to get things green :)

**Comment by Anton-4** [comment]
I take Sundays off but I don't think the remaining fixes were difficult, I'll get back in touch on Monday if I need help.

**Comment by JanCVanB** [comment]
Thank you, @Anton-4 ! Absolutely, enjoy your Sunday.

**Comment by Anton-4** [comment]
The benchmarks are unavoidably failing because it's trying to compare trunk and the branch and it expects both to have the same folder structure.
I made the cli_run tests run faster but the speedup is not nearly as large as I expected so I want to look into that a bit more.

**Comment by Anton-4** [comment]
The speedup that was smaller than expected is most likely explained by cargo caching.

**Comment by JanCVanB** [comment]
@Anton-4 How should we approach merging this? Merge when red because confident, then be ready to fix main if anything happens?

**Comment by JanCVanB** [comment]
Also please check any TODO boxes you finished in your many helpful commits :)

**Comment by Anton-4** [comment]
> How should we approach merging this?

I've changed the benchmarks to compare against itself instead of against main. Once merged we can do a new PR to compare against main again.

**Comment by Anton-4** [comment]
I think the nix apple silicon failure can be fixed by using the [serial_test crate](https://docs.rs/serial_test/latest/serial_test/), I'll try that tomorrow.

**Comment by JanCVanB** [comment]
I can try resolving conflicts, unless your perspective is needed on that

**Comment by Anton-4** [comment]
I was able to resolve the conflicts quickly, let's hope all tests pass now :crossed_fingers:

**Comment by Anton-4** [comment]
I'd like to merge this soon. This PR accumulates merge conflicts very quickly and contains a fix for flaky test errors that occur most often on macos 11 x86_64. There are lot of roctoberfest days left, waiting until say 90% of people is done would take a long time. 

btw the last two TODO's have not been completed, this PR is already large so I'd like to keep that for a follow-up PR.

**Comment by JanCVanB** [comment]
Great points, so let's merge this today with communication

**Comment by JanCVanB** [comment]
@Anton-4 Let's do this!

**Review by Anton-4 — APPROVED** [review]

**Comment by Anton-4** [comment]
:tada:

**Pull request merged**
