### PR TITLE
made nix flake work for darwin

### PR DESCRIPTION
**Pull request by Anton-4**

### CODE REVIEW

**Comment by dvic** [comment]
Does this still work? I just tried `nix shell github:roc-lang/roc/ac45fa2bba87f46a30394293dcd13556f7cdebf4`

and got

```
❯ nix shell github:roc-lang/roc/ac45fa2bba87f46a30394293dcd13556f7cdebf4
error: builder for '/nix/store/h9z2plxdnzig87zkm14v2qc2vkqwgw80-zig-0.9.1.drv' failed with exit code 134;
       last 10 log lines:
       > [ 98%] Built target zig0
       > [ 99%] Building self-hosted component /tmp/nix-build-zig-0.9.1.drv-0/source/build/zig1.o
       > [ 99%] Building CXX object CMakeFiles/zig.dir/src/stage1/empty.cpp.o
       > [100%] Linking CXX executable zig
       > [100%] Built target zig
       > buildPhase completed in 1 minutes 42 seconds
       > running tests
       > thread 175698 panic: Darwin is handled separately via std.zig.system.darwin module
       > Unable to dump stack trace: debug info stripped
       > /nix/store/gn9v8p0m68wj3ss5lyz1pq8s568l8w4a-stdenv-darwin/setup: line 1407: 44423 Abort trap: 6           ./zig test --cache-dir "$TMPDIR" -I $src/test $src/test/behavior.zig
       For full logs, run 'nix log /nix/store/h9z2plxdnzig87zkm14v2qc2vkqwgw80-zig-0.9.1.drv'.
error: 1 dependencies of derivation '/nix/store/g9dk4hqv9d4z4vcpxsd26wdgc1s2lswp-roc-0.0.1.drv' failed to build
```

**Comment by Anton-4** [comment]
Hi @dvic, it looks like you're encountering this [zig issue](https://github.com/ziglang/zig/issues/10478) because you are on macos 13. You should be able to use the macos nightly as long as you're not building custom zig platforms or using wasm.

**Comment by Anton-4** [comment]
The latest macos nightlies are broken so you'll want to use the 01-17. I'm working on fixing them now.

**Comment by dvic** [comment]
> Hi @dvic, it looks like you're encountering this https://github.com/ziglang/zig/issues/10478 because you are on macos 13. 

> The latest macos nightlies are broken so you'll want to use the 01-17. I'm working on fixing them now.

nice 👍, thanks for the prompt response!

Running `nix shell github:roc-lang/roc/7b8783ae0d4c2a51b3b53535a4c9683f2f6ca0f3` (latest [commit](https://github.com/roc-lang/roc/commit/7b8783ae0d4c2a51b3b53535a4c9683f2f6ca0f3) of 01-17) gives the same error. 

> You should be able to use the macos nightly as long as you're not building custom zig platforms or using wasm.

Did you mean that I have to change something in the nix config file? Or that I have to wait for a fix in zig itself?

**Comment by Anton-4** [comment]
Apolagies, for the 01-17 nightly I did not mean the commit but meant from the prebuilt tar.gz [here](https://github.com/roc-lang/roc/releases).

To be able to build from source again on macos 13, we are waiting on zig 10 to be available on nix.

**Pull request merged**
