### PR TITLE
add missing indent when formatting single-quoted char in pattern

### PR DESCRIPTION
**Pull request by austinclem1**
As mentioned in issue #4428

### CODE REVIEW

**Review by ayazhafiz — COMMENTED** [review]
Thanks! Would you mind adding a test to https://github.com/roc-lang/roc/blob/87041f8cd70efc4290724f2d2d0b6d95e63d5bbd/crates/compiler/fmt/tests/test_fmt.rs?

**Comment by austinclem1** [comment]
Sure thing, just realizing I have to get tests running on here lol. I'm new to nix but building roc has been working from a `nix develop` shell in WSL. Should I be able to just run `cargo test` from the same shell?

**Comment by austinclem1** [comment]
Oh also I called the test `when_with_single_quoted_char`, does that work? I realize the word char has come to mean different things with unicode and all that so if there's a more roc-specific term I can change it

**Comment by ayazhafiz** [comment]
yeah, you should be able to - and you can scope to just the formatter package with `cargo test -p roc_fmt`.

The test name seems reasonable!

**Comment by austinclem1** [comment]
Cool! Confirmed that the test only passes after the new change

**Comment by austinclem1** [comment]
Whoops, will run rustfmt shortly

**Review by rtfeldman — APPROVED** [review]
Lovely, thank you @austinclem1! 🎉

**Pull request merged**
