### PR TITLE
windows cross compilation

### PR DESCRIPTION
**Pull request by folkertdev**
attempt to compile for windows from any platform. 

This now works

```
target/debug/roc build --precompiled-host=false --linker=legacy --target=windows64 examples/platform-switching/zig-platform/rocLovesZig.roc
```

but running it does not yet work with wine, for me. It would be cool if someone on windows could compile this branch and run the above command within WSL, and then try to run the exe on windows.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Whoa, Linux `ld` can link windows executables? 😲

**Comment by folkertdev** [comment]
I think it's `lld` with the correct flags, yes (that is what zig calls)

**Comment by folkertdev** [comment]
Running with wine now also works, for simple zig platforms at least

**Review by rtfeldman — APPROVED** [review]
Looks good! 💯

**Pull request merged**
