### PR TITLE
Add missing functions to Result

### PR DESCRIPTION
**Pull request by rudolfvesely**
Add missing functions setOk and setErr to Result.

### CODE REVIEW

**Comment by folkertdev** [comment]
in what sort of cases is this useful? Wouldn't `mapOk` and `mapErr` suffice in those cases?

**Comment by rudolfvesely** [comment]
I used it like this:
```
|> ...
|> findFirst ...
|> setErr UserNotFound # instead of NotFound
|> ...
```

**Comment by folkertdev** [comment]
right, but that could be 

```
|> ...
|> findFirst ...
|> Result.mapErr \_ -> UserNotFound # instead of NotFound
|> ...
```

which I think is clearer because it explicitly dismisses the current value

**Comment by rudolfvesely** [comment]
I tried that and a pipe with a function followed by setErr instead of lambda looks very organized. But feel free to close the PR if it doesn't align with Roc's strategy.

**Comment by lukewilliamboswell** [comment]
@rudolfvesely I am going to close this PR as there hasn't been any further discussion on this. But, please re-open or raise a new discussion on zulip if you would like to discuss these ideas further.

**Pull request closed without merging**
