### PR TITLE
Report lacking `to` while parsing app header

### PR DESCRIPTION
**Pull request by caryoscelus**

### CODE REVIEW

**Comment by Anton-4** [comment]
Thanks for helping out @caryoscelus! Could you add a test for this as well?

**Comment by caryoscelus** [comment]
@Anton-4 sure! it seems there's also a lot of space to lower code repetition while i'm at it

**Comment by caryoscelus** [comment]
> there's also a lot of space to lower code repetition while i'm at it

on second thought, probably condensing code isn't worth here

@Anton-4 ready for review

**Review by Anton-4 — APPROVED** [review]
Looks good, thanks @caryoscelus!

**Pull request merged**
