### PR TITLE
Improve consistency in CLI help messages

### PR DESCRIPTION
**Pull request by JanCVanB**
I just noticed some minor inconsistencies.

### CODE REVIEW

**Comment by JanCVanB** [comment]
Would anyone prefer no trailing periods on these sentence fragments? I started to do that, but then I realized that periods scale better to other parts of the help message and also to longer descriptions.

**Comment by JanCVanB** [comment]
Hmm, now I'm back to leaning toward wanting no trailing periods. It's trivial, but perhaps it's good to follow the `clap` library's convention...

**Comment by JanCVanB** [comment]
Yeah, I switched from trailing periods to no trailing periods (and newlines for separating additional info)

**Review by rtfeldman — APPROVED** [review]
Cool, thanks @JanCVanB! 🎉

**Pull request merged**
