### PR TITLE
Linking example pages to source code

### LINKED ISSUE #6151: Every website examples page should have a link to the source
So in https://www.roc-lang.org/examples/IngestFiles/README.html there should be a link to https://github.com/roc-lang/examples/tree/main/examples/IngestFiles

### PR DESCRIPTION
**Pull request by fyuan1316**
close #6151

### CODE REVIEW

**Comment by fyuan1316** [comment]
@Anton-4  
Script split is done. PTAL :）

**Review by Anton-4 — CHANGES_REQUESTED** [review]
Thanks @fyuan1316, I split some things up with variables to make the code easier to understand. Could you move the perl part to add-link.pl? A neat multiline script is easier to understand and add comments to.

**Comment by fyuan1316** [comment]
@Anton-4 
Okay, I'll finish up later. 
Just a quick question. For the variable that holds the example repo prefix, shouldn't its value be `https://github.com/roc-lang/examples/tree/main/examples`? 

image

**Comment by Anton-4** [comment]
> Just a quick question. For the variable that holds the example repo prefix, shouldn't its value be https://github.com/roc-lang/examples/tree/main/examples?

Oops, yes that's correct :)

**Comment by fyuan1316** [comment]
@Anton-4 
Done. PTAL :)

**Comment by Anton-4** [comment]
Thanks @fyuan1316 :)
I have not forgotten about this PR, I decided to rewrite the bash+perl script in Roc to avoid adding another programming language (perl) to the repo. I should be finished tomorrow.

**Comment by Anton-4** [comment]
I got blocked on a Roc compiler bug, so I'm going to read over the perl version again and merge this on Friday :)

**Review by Anton-4 — APPROVED** [review]
Thanks @fyuan1316 :)

**Comment by Anton-4** [comment]
Can you merge this @rtfeldman?

**Pull request merged**
