### PR TITLE
Add Dict module to the testing CI

### PR DESCRIPTION
**Pull request by cjduncana**
This MR adds a command for testing the Dict module in the CI. I also added an example of how to use `Dict.update` with instructions on how to add and view said comments.

### CODE REVIEW

**Comment by cjduncana** [comment]
`Dict.update` in the Standard Library page with the updated comment:
Screen Shot 2022-10-10 at 9 34 33 AM

**Comment by cjduncana** [comment]
I want to figure out how to test a whole directory instead of per file.

**Comment by ayazhafiz** [comment]
@cjduncana to test a whole directory instead of just a file, we'll need to modify the compiler's [loading mechanism](https://github.com/roc-lang/roc/blob/5a7211d874224c9bb6f8a709bb5f41ec383286c1/crates/compiler/load_internal/src/file.rs#L1759) to support processing a whole directory at a time in test mode - I'm happy to chat through how to do this if you're interested on the Zulip thread you started, but fair warning, it might be a lot of work 😅 Otherwise, we can file an issue for it

**Comment by cjduncana** [comment]
[Zulip topic](https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/.60roc.20test.60.20multiple.20files) referred above.

**Review by ayazhafiz — DISMISSED** [review]

**Review by rtfeldman — DISMISSED** [review]

**Review by folkertdev — APPROVED** [review]

**Pull request merged**
