### PR TITLE
Expression indentation syntax error

### PR DESCRIPTION
**Pull request by TimWhiting**
I ran into this syntax error a lot today trying to do the Advent of Code

Mostly when adding commenting out the next line

### CODE REVIEW

**Comment by JanCVanB** [comment]
@Anton-4 Could you (or someone else) please add such a test? This looks like a great enhancement.

**Comment by TimWhiting** [comment]
As an update from my end. I attempted to add a test, but got stuck and could not figure it out.

**Comment by JanCVanB** [comment]
@TimWhiting Would you like assistance adding such a test yourself?

**Comment by TimWhiting** [comment]
> @TimWhiting Would you like assistance adding such a test yourself?

Sure, if you want, I can make some time next week to pair program a test for this.

**Comment by JanCVanB** [comment]
Nice! Let me know when you're available.

**Comment by TimWhiting** [comment]
I was able to figure out the test & rebase on the latest main. Moved these changes to my fork, and opened a new PR #4131

**Pull request closed without merging**
