### PR TITLE
Add `Str.replace*` builtins

### PR DESCRIPTION
**Pull request by JanCVanB**
Blocked by https://github.com/roc-lang/roc/issues/4018

### CODE REVIEW

**Comment by JanCVanB** [comment]
Why can't I get the REPL to pick up on my changes? Is it related to #4018?
```
[jan@framey roc]$ cargo run repl
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/roc repl`

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» Str.replaceFirst

── NOT EXPOSED ─────────────────────────────────────────────────────────────────

The Str module does not expose `replaceFirst`:

4│      Str.replaceFirst
        ^^^^^^^^^^^^^^^^

Did you mean one of these?

    Str.splitFirst
    Str.repeat
    Str.split
    Str.splitLast


» 
```

**Comment by rtfeldman** [comment]
@JanCVanB I pushed some fixes - the reason they weren't showing up as exposed is that builtins need to be manually registered in `Symbol` - see https://github.com/roc-lang/roc/pull/4019/commits/2030774e6838f473797eb5c165c6fe77b0f1d551

I also fixed some type mismatches and added some tests!

**Comment by JanCVanB** [comment]
My hero!

**Comment by JanCVanB** [comment]
I'll never forget about `Symbol` again.

**Comment by JanCVanB** [comment]
It works! Ready to merge!

**Review by rtfeldman — APPROVED** [review]

**Pull request merged**
