### PR TITLE
Fixed Integer casting

### PR DESCRIPTION
**Pull request by wizard7377**
Fixed the problem of integer casting, particularly casting unsigned to signed numbers, fixing #7184

### CODE REVIEW

**Review by lukewilliamboswell — DISMISSED** [review]
Thank you 😃

**Comment by wizard7377** [comment]
Sorry I havent used git in a while and have managed to severly screw this up

**Review by lukewilliamboswell — APPROVED** [review]

**Review by lukewilliamboswell — DISMISSED** [review]

**Comment by lukewilliamboswell** [comment]
@wizard7377 that CI failure looks significant, are you able to investigate?

```
     Summary [  98.658s] 962 tests run: 961 passed, 1 failed, 6 skipped
        FAIL [   0.068s] test_gen::test_gen gen_num::cast_signed_unsigned
```

**Comment by wizard7377** [comment]
Oh dear me 
Yeah the test I added should probably be passing shouldn't it

**Review by lukewilliamboswell — APPROVED** [review]

**Pull request merged**
