### PR TITLE
Implement `List.sortAscBy` and `List.sortDescBy` builtins

### LINKED ISSUE #6988: `sortAscBy : List elem, (elem -> Num *) -> List elem`

### LINKED ISSUE #6989: `sortDescBy : List elem, (elem -> Num *) -> List elem`

### PR DESCRIPTION
**Pull request by lukewilliamboswell**
Closes #6988 
Closes #6989

### CODE REVIEW

**Comment by lukewilliamboswell** [comment]
Test failure on linux x64 CI caused by the following
```
--- STDERR:              test_gen::test_gen gen_list::list_sort_asc_by ---
An internal compiler expectation was broken.
This is definitely a compiler bug.
Please file an issue here: <https://github.com/roc-lang/roc/issues/new/choose>
Cannot load no data into general registers: `#UserApp.IdentId(65)`
Location: crates/compiler/gen_dev/src/generic64/storage.rs:544:17
```

**Comment by smores56** [comment]
Is this really the right API? Since we have https://www.roc-lang.org/builtins/Num#compare, I think it would be better to use a `a, a -> [LT, GT, EQ]` comparator if possible. What do you think @lukewilliamboswell ?

**Comment by lukewilliamboswell** [comment]
> Is this really the right API? Since we have https://www.roc-lang.org/builtins/Num#compare, I think it would be better to use a `a, a -> [LT, GT, EQ]` comparator if possible. What do you think @lukewilliamboswell ?

I don't have a strong opinion here, and I had the same thought. I was implementing the API detailed in [the linked Issue](https://github.com/roc-lang/roc/issues/664) -- and so deferred my question on that until now. I figured we can close this PR if it is no longer needed - it was only a few minutes work to add this.

My thoughts are that I'm not sure -- the API is similar, but maybe it is useful for some use-cases and that is why it was included alongside the others.

I'll ask in zulip for ideas.

**Comment by lukewilliamboswell** [comment]
Closing as no longer planned. Superseded by #7006

**Pull request closed without merging**
