### PR TITLE
WIP: Json decoding

### PR DESCRIPTION
**Pull request by Qqwy**
This PR is a work-in-progress effort to decode JSON values.

### CODE REVIEW

**Comment by ayazhafiz** [comment]
@Qqwy it would be great to land this, and perhaps eventually integrate it with the Encode/Decode ability! Can we help with getting this ready to land?

**Comment by rtfeldman** [comment]
@Qqwy I know you've got other things on your plate, so I'd love to take this over and get it into `main`! 😃 

Any objection to my doing that?

**Comment by Qqwy** [comment]
Yes, please go ahead! :heart:

**Comment by rtfeldman** [comment]
I think as of https://github.com/roc-lang/roc/pull/5077 (and other JSON things leading up to it), this can be closed...we can always reopen it in the future if desired!

Thanks again for working on this @Qqwy! 🎉

**Pull request closed without merging**
