### PR TITLE
builtin(str): add Str.withPrefix

### LINKED ISSUE #4142: Str.withPrefix builtin
We should have a builtin like this:

```elixir
## Like [Str.concat] but with the arguments reversed.
##
## This is useful in pipelines, for example:
##
##     "World!"
##     |> Str.withPrefix "Hello, "
##     # "Hello, World!"
withPrefix : Str, Str -> Str
withPrefix = \str, prefix -> Str.concat prefix str
```

### PR DESCRIPTION
**Pull request by snprajwal**
Requires rebase and increment in `symbols.rs` after merging #4237. Or we can merge this first and rebase that PR, either ways is fine.

Closes #4142

### CODE REVIEW

**Review by ayazhafiz — APPROVED** [review]
LGTM after tests pass

**Comment by rtfeldman** [comment]
Unfortunately, looks like this picked up some merge conflicts after https://github.com/roc-lang/roc/pull/4249 landed!

**Comment by snprajwal** [comment]
> Unfortunately, looks like this picked up some merge conflicts after https://github.com/roc-lang/roc/pull/4249 landed!

I think it's due to #4237 being merged, I'll fix it and push shortly!

**Review by rtfeldman — APPROVED** [review]

**Pull request merged**
