### PR TITLE
macOS x86_64 test workflow

### PR DESCRIPTION
**Pull request by Anton-4**

### CODE REVIEW

**Review by rtfeldman — DISMISSED** [review]
Cool, looks good! 👍

**Comment by rtfeldman** [comment]
Just noting that this is unblocked now - so we can at least change the title! 😄

**Comment by rtfeldman** [comment]
I guess this is now only blocked on a merge conflict?

**Comment by Anton-4** [comment]
Well, the reason I have not made this a priority is because running tests alone (without building) take around an hour and 10 minutes already. I think I'll slim this down to just the `cli_run` tests and keep running the full test suite once a day.

**Comment by rtfeldman** [comment]
Makes sense! 👍

**Review by folkertdev — APPROVED** [review]

**Pull request merged**
