### PR TITLE
lock zig platform building

### PR DESCRIPTION
**Pull request by Anton-4**
I was sometimes getting the following errors for the zig platform-switching and parse_movies cli_run tests:
```
thread '<unnamed>' panicked at 'failed to open file "/home/username/gitrepos/roc3/roc/examples/parser/examples/../../platform-switching/zig-platform/dynhost": No such file or directory (os error 2)', crates/linker/src/lib.rs:511:29
```
and
```
Inconsistency detected by ld.so: dl-setup_hash.c: 36: _dl_setup_hash: Assertion `(bitmask_nwords & (bitmask_nwords - 1)) == 0' failed!
```
These errors seemed to occur due to multiple tests simultaneously building the zig platform, I've locked this building using `serial` and ran roc_cli tests 6 times to confirm the issue was fixed.

Updates in the Cargo.lock files are because I ran related tests locally after #5062 was merged in.

### CODE REVIEW

**Comment by brian-carroll** [comment]
> Updates in the Cargo.lock files are because I ran related tests locally after https://github.com/roc-lang/roc/pull/5062 was merged in.

Hmm this sort of thing can cause issues though! I'd be more comfortable removing diffs that aren't needed for the PR.
```
git checkout origin/main examples
```

**Comment by brian-carroll** [comment]
@Anton-4 were those diffs needed? I thought you suggested they weren't but then the build failed.

**Comment by Anton-4** [comment]
I re-ran that test, I think it might be a flaky failure.

The diffs are not required but I think they should be added, for the rest of the project we use `cargo [...] --locked` to see if the lock files are up to date but we can't really do this here because they are rust platform for examples. Rust recommendations are to add lock files to your repo and keep them up to date.

**Comment by brian-carroll** [comment]
Oh ok I misunderstood. I'll put them back then.

**Comment by brian-carroll** [comment]
It's back on the same commit, sorry for the confusion.

**Review by brian-carroll — DISMISSED** [review]

**Comment by Anton-4** [comment]
No problem :)

**Review by brian-carroll — APPROVED** [review]

**Pull request merged**
