### PR TITLE
Give better error messages when provides is missing in header

### PR DESCRIPTION
**Pull request by KilianVounckx**
Fixes [this issue](https://github.com/roc-lang/roc/issues/5516)

### CODE REVIEW

**Comment by Anton-4** [comment]
Thanks @KilianVounckx :)
Could you add a test for this case (as shown in the issue) as well?

**Comment by KilianVounckx** [comment]
Do I just add a test at the end of `crates/reporting/tests/test_reporting.rs` for this?

**Comment by Anton-4** [comment]
It would probably be best to add it after [this test](https://github.com/roc-lang/roc/blob/7b19a1552c4579df936be4d7df9e8e3e94293716/crates/reporting/tests/test_reporting.rs#L5913)

**Review by Anton-4 — APPROVED** [review]
Looks good!

**Pull request merged**
