### PR TITLE
Tutorial: add spaces before colons

### PR DESCRIPTION
**Pull request by human154**

### CODE REVIEW

**Comment by lukewilliamboswell** [comment]
@human154 thankyou for your contribution, however this is an intentional design choice. You can read more about record syntax in zulip in this [discussion thred](https://roc.zulipchat.com/#narrow/stream/304641-ideas/topic/Record.20Syntax/near/327994809)

**Comment by human154** [comment]
@lukewilliamboswell 

My understanding of the "proper" syntax here is based on what Richard Feldman wrote on Zulip:

"in Roc today:

always, what comes before = is a pattern
always, an identifier followed by a : is a record field declaration
always, an identifier followed by a blank space and then a : is a type declaration
"

(the last line of that quote being relevant here.)

**Comment by lukewilliamboswell** [comment]
I think we can check with the roc formatter. I'll make a sample file and see what the default behaviour is. I personally like the spaces before, I think it looks neater. There's been a few PRs recently which have *fixed* this, so worth double checking. Apologies if I closed this prematurely.

**Comment by human154** [comment]
Ok, Great! Thanks Luke!

**Review by lukewilliamboswell — APPROVED** [review]
Fix spaces in tutorial for record types.

**Comment by lukewilliamboswell** [comment]
@Anton-4 @rtfeldman can we merge this PR? Do we need to push an update to restart CI or something?

**Comment by Anton-4** [comment]
I've restarted the workflow, the PR will merge automatically when it passes.

**Pull request merged**
