### PR TITLE
WIP Add sqlite example

### PR DESCRIPTION
**Pull request by asteroidb612**

### CODE REVIEW

**Comment by JanCVanB** [comment]
@asteroidb612 Thank you for this! Are you still working on it? Would you like a review and/or some assistance?

**Comment by asteroidb612** [comment]
Thanks for asking! I have had more ideas about this and would like some
assistance thinking them through. If you're cleaning up, close this and I
can reopen when I figure that out!

**Comment by JanCVanB** [comment]
Awesome, will do. Want to open a thread in [the Roc chatroom](https://roc.zulipchat.com) to discuss?

**Comment by JanCVanB** [comment]
Alternatively, if you want help here, I could CC someone who can help :)

**Pull request closed without merging**
