### PR TITLE
wasm 32 cli run fixes, added to ci tests

### PR DESCRIPTION
**Pull request by Anton-4**
@brian-carroll  when refactoring `cli_run.rs` in PR #4015 I noticed the `wasm32_cli_run` tests contained build errors and so they were also not being tested on CI. I fixed up the imports and added tests to `nix_linux_x86_64.yml`. I do assume we want this tested in CI?

All `wasm32_cli_run` `benchmark_tests` are currently failing with:
```
/home/anton/gitrepos/roc7/roc/crates/cli_testing_examples/benchmarks/platform/host.zig:192:68: error: no member named 'error_code' in struct 'GetInt'
        const get_int = GetInt{ .is_error = false, .value = value, .error_code = false };
```
Can you take a look at this @brian-carroll?

### CODE REVIEW

**Comment by folkertdev** [comment]
what should I run to reproduce? 

```
> cargo test --test cli_run benchmark
    Finished test [unoptimized + debuginfo] target(s) in 0.68s
     Running tests/cli_run.rs (target/debug/deps/cli_run-3b1e4c4ef8a76a78)

running 10 tests
test cli_run::test_benchmarks::quicksort_app ... ok
test cli_run::test_benchmarks::issue2279 ... ok
test cli_run::test_benchmarks::closure ... ok
test cli_run::test_benchmarks::nqueens ... ok
test cli_run::test_benchmarks::cfold ... ok
test cli_run::test_benchmarks::astar ... ok
test cli_run::test_benchmarks::rbtree_ck ... ok
test cli_run::test_benchmarks::rbtree_insert ... ok
test cli_run::test_benchmarks::base64 ... ok
test cli_run::test_benchmarks::deriv ... ok
```

works on my machine

**Comment by brian-carroll** [comment]
Sorry guys, should have provided more context.

The command to run is
```
cargo test -p roc_cli --features=wasm32-cli-run test_benchmarks::base64 
```

This runs one test only, not multiple in parallel.

**Comment by folkertdev** [comment]
It looks like some logic got lost for turning that `.bc` into a `.o`

I also noticed we're making llvm bytecode for the `i386` target there. Ideally we wouldn't, because LLVM IR is not portable. Just using the wasm target runs into an error though (main is then defined twice, apparently).

**Comment by brian-carroll** [comment]
wasm-ld actually accepts .bc files, as weird as that is
https://github.com/llvm/llvm-project/blob/main/lld/wasm/InputFiles.h#L170

**Comment by folkertdev** [comment]
I can now do 

    > cargo run -- build --target=wasm32 crates/cli_testing_examples/benchmarks/NQueens.roc
        Finished dev [unoptimized + debuginfo] target(s) in 14.66s
         Running `target/debug/roc build --target=wasm32 crates/cli_testing_examples/benchmarks/NQueens.roc`
    🔨 Rebuilding platform...
    0 errors and 0 warnings found in 1055 ms while successfully building:

        crates/cli_testing_examples/benchmarks/nqueens.wasm
    > wasmtime  crates/cli_testing_examples/benchmarks/nqueens.wasm

    Please enter an integer
    5
    10
    runtime: 2212.379ms

Now what we need to is actually decide how to run this. I think what is happening right now is that we just run `./nqueens.wasm` and on linux obviously `.wasm` is not a valid executable.

**Comment by brian-carroll** [comment]
Great, nice work!
Ideally we would use wasm3 but we currently only have it as a library, not as an executable.

**Comment by folkertdev** [comment]
there was some existing wasmer code to run the wasm, so I just used that for now. Tests now run on my machine, so if CI fails on this it's likely that something is not installed

**Comment by folkertdev** [comment]
@Anton-4 I think this is good to merge?

**Review by folkertdev — APPROVED** [review]

**Comment by Anton-4** [comment]
Yes, all good! Thanks @folkertdev and @brian-carroll :heart:

**Pull request merged**
