### PR TITLE
added copy button to tutorial code blocks

### PR DESCRIPTION
**Pull request by swork1**
I have added a copy button to code blocks in response to issue #5137 . The copy button only shows up on hover
 Screenshots below
image
image

### CODE REVIEW

**Comment by swork1** [comment]
I think adding this to the documentation for builtins would also be beneficial?

**Comment by lukewilliamboswell** [comment]
@Anton-4 this looks good to me.

> I think adding this to the documentation for builtins would also be beneficial?

I agree. The assets for docs are located in `crates/docs/src/static`. 

I have been trying to slowly merge the two styles, with the intent to have one `.css` file for the Docs, Tutorial, (possibly Examples) and other content too.

**Review by lukewilliamboswell — APPROVED** [review]

**Comment by Anton-4** [comment]
Hmm, I got an `Uncaught TypeError: navigator.clipboard is undefined` when testing locally. But this [W3Schools example](https://www.w3schools.com/howto/tryit.asp?filename=tryhow_js_copy_clipboard) did work for me, it could just be some weird issue that would not occur when the site is actually deployed :shrug: we'll see once it's live :p

**Review by Anton-4 — APPROVED** [review]
Thanks @swork1!

Based on the "browser smartphone view" I could not get the copy button to show, for smartphones it would be nice to have a permanent button, added with js so not originally in the HTML. But we can leave that for another PR.

**Comment by swork1** [comment]
> Thanks @swork1!
> 
> Based on the "browser smartphone view" I could not get the copy button to show, for smartphones it would be nice to have a permanent button, added with js so not originally in the HTML. But we can leave that for another PR.

Yea I forgot to check mobile, mobile doesn't have "hover". I can write up a "touchSupported" function for a permanent copy button. Good callout

**Pull request merged**
