### PR TITLE
Arena allocation example

### PR DESCRIPTION
**Pull request by dullbananas**

### CODE REVIEW

**Comment by JanCVanB** [comment]
@dullbananas @folkertdev @bhansconnect Do you still want this? An arena allocator example sounds like a great thing to have, do any of our other examples today happen to use such a system?

**Comment by dullbananas** [comment]
None of the other example platforms have arena allocation or anything else that doesn't just call `malloc`, so this example should still be added

**Comment by JanCVanB** [comment]
Any known issues with this PR? Maybe just rebasing would heal some of the testing issues?

**Comment by bhansconnect** [comment]
I think it is mostly a matter of updating to latest roc and maybe modifying the platform slightly.

**Pull request closed without merging**
