### PR TITLE
Add missing titles and descriptions

### PR DESCRIPTION
**Pull request by kukimik**
I found the lack of titles in some pages slightly annoying. Also, AFAIK, empty `<title>` tag is an HTML error.

Disclaimer: I did not try building the site, sorry. Looks like it should work, but I'm not sure about `repl/index.html`. My English is not perfect, so please take a close look at it before merging!

It could be a good idea to include the titles and descriptions in the `.md` files (some YAML frontmatter? using the top header as page title ?). Currently it's easy to forget about adding the title to `main.roc`  when creating a new page.

### CODE REVIEW

**Comment by ayazhafiz** [comment]
@rtfeldman / @Anton-4  you are likely the most familiar here, PTAL

**Review by Anton-4 — APPROVED** [review]
Thanks @kukimik!

Title space is limited so I shortened this a bit. I also shortened the description. It's always better for things to be shorter if we can convey the same amount of information.

I made the code crash if the title is missing, that seems like the least complex fix.

**Comment by kukimik** [comment]
Fixed a typo.

> Title space is limited so I shortened this a bit. I also shortened the description.

Thanks. I tried to follow the style of the existing titles/descriptions, but certainly got too verbose at times.

The shortened titles, not containing the word `Roc`, may not work very well out of context of this website (e.g. in the result list of a Google search). I'd consider bringing the word `Roc` back.

> I made the code crash if the title is missing, that seems like the least complex fix.

:+1: 

Would be nice if this could also work for https://www.roc-lang.org/examples.

**Comment by Anton-4** [comment]
> The shortened titles, not containing the word Roc, may not work very well out of context of this website (e.g. in the result list of a Google search). I'd consider bringing the word Roc back.

Sorry, I'm confused, all the titles already contain the word Roc.

> EDIT: I think that keeping the information that Roc is a programming language in the descriptions may also be a good idea, because it gives some context...

Yeah, good idea, I'll update that.

> Would be nice if this could also work for https://www.roc-lang.org/examples.

Good idea, I made #6741 for that.

**Review by Anton-4 — DISMISSED** [review]

**Review by Anton-4 — APPROVED** [review]

**Comment by kukimik** [comment]
> > The shortened titles, not containing the word Roc, may not work very well out of context of this website (e.g. in the result list of a Google search). I'd consider bringing the word Roc back.
> 
> Sorry, I'm confused, all the titles already contain the word Roc.

Ah, sorry, I somehow missed the part of the title after the pipe symbol when looking at the diff.

Thanks for taking care of this PR @Anton-4!

**Pull request merged**
