### PR TITLE
Implement Num.isZero as a low-level

### LINKED ISSUE #4223: Add a Num.isZero low-level
We'll need a new low-level `IsZero` to implement `isZero : Num a -> Bool`, since with the `Eq` ability, `isZero = \n -> n == 0` will not check, as `F32`/`F64` cannot be compared to 0!

### PR DESCRIPTION
**Pull request by ayazhafiz**
This will be needed ahead of the `Eq` ability.

Closes #4223

### CODE REVIEW

**Review by folkertdev — COMMENTED** [review]
for my understanding: why is it important that this function is defined in roc code? you could just call `Num.isZero` in generated code right?

**Comment by ayazhafiz** [comment]
Because other functions in Num.roc check for == 0, so otherwise we must generate them too

**Comment by folkertdev** [comment]
I still don't understand: what makes the generated version different from one generated by roc code?

**Comment by ayazhafiz** [comment]
Oh. The generated one is calling the low-level directly. The Roc code is calling `Bool.eq`, which after `Eq` ability, will be calling `Eq.eq`. But calling `Eq.eq` inherits an `Eq` constraint on the number variable, which we can't fulfill for `Float`. So to get around that, we want to call the eq low-level directly instead.

**Review by folkertdev — APPROVED** [review]
makes sense

**Pull request merged**
