### PR TITLE
Add Str.contains to builtins

### LINKED ISSUE #5900: Add String `contains` builtin
See [this commit](https://github.com/roc-lang/roc/pull/5893/commits/b7923ac54215d310a957f40f6e5b95952a2d172a) that adds a builtin to List for an example to follow.

### PR DESCRIPTION
**Pull request by isaacvando**
Closes #5900.

### CODE REVIEW

**Review by bhansconnect — DISMISSED** [review]
Looks Great! 🚀

**Comment by bhansconnect** [comment]
Ah yeah, mono and ui tests. They generally change whenever the builtins change.

Can you run `cargo test -p uitest -p roc_mono` and add the changed files.

**Review by bhansconnect — APPROVED** [review]

**Comment by isaacvando** [comment]
@bhansconnect Out of curiosity, what are those files? Also, is `test_mono` not included when you run `cargo test` because it generates changes?

**Comment by bhansconnect** [comment]
Those are tests that deal with come of the more complex type system and monomorphization code in Roc. They are easier to work with when outputting a fully visual form of the roc ast that looks like regular code. So when someone changes monomorphization, they can visually see what gets generated. Sadly, they also change when the code itself changes. So we often have to run them for other builtin changes.

They should run with just `cargo test` from the workspace directory.

**Comment by isaacvando** [comment]
Cool, thanks for the info

**Pull request merged**
