### PR TITLE
New docs template

### PR DESCRIPTION
**Pull request by gamebox**
~~Just a prototype~~

This is now being merged in earnest.

Desktop (Light/Dark mode side-by-side):
Screenshot 2024-12-18 at 8 47 45 AM

Desktop w/ Search (Light/Dark side-by-side):
Screenshot 2024-12-18 at 8 52 20 AM

Mobile(Dark mode):
Screenshot 2024-12-18 at 8 48 10 AM

Mobile w/ Sidebar open (Dark mode):
Screenshot 2024-12-18 at 8 48 53 AM

Mobile w/ Search open (Dark mode):
Screenshot 2024-12-18 at 8 49 26 AM

Mobile (light mode):
Screenshot 2024-12-18 at 8 50 04 AM

Mobile w/ Sidebar open (Light mode):
Screenshot 2024-12-18 at 8 51 26 AM

Mobile w/ Search open (Light mode):
Screenshot 2024-12-18 at 8 51 44 AM

### CODE REVIEW

**Comment by Anton-4** [comment]
The difference in colors for syntax highlighting has reduced significantly, could we re-use the old colors here?
Screenshot from 2024-12-18 16-26-44
left is current version | right is new

**Comment by gamebox** [comment]
The old colors are not AAA compliant. Comment in CSS notwithstanding

**Comment by gamebox** [comment]
I can try playing with the saturation some more

**Review by Anton-4 — DISMISSED** [review]
> I can try playing with the saturation some more

Yes, I do think that is worth it.

All the rest looks good :)

**Comment by gamebox** [comment]
My newest changes will move the Dark Mode syntax highlighting to this color palette.

Screenshot 2024-12-18 at 4 34 48 PM

**Comment by gamebox** [comment]
I think the light mode syntax highlighting is good to go already

**Review by lukewilliamboswell — APPROVED** [review]

**Comment by kukimik** [comment]
@gamebox This has broken the highlighting of the current (`:target`) entry-name, see #7299 and #7382.

In #7382 I used `background-color: var(--violet-bg);` to highlight the entry pointed at by the  `#fragment` part of the URI. But now all entries have this background color:

https://github.com/roc-lang/roc/blame/eda4db05894dd027b023803f8c9ffbc559b6900a/crates/docs/src/static/styles.css#L74

If we want to use this background color for all entries, then perhaps the border style can be used to distinguish the current entry (have a look at the screenshots in #7382)?

**Pull request merged**
