### PR TITLE
Implement builtins for Num.isNan, Num.isInfinite, and Num.isFinite

### LINKED ISSUE #5309: Implement builtin for `Num.isInfinite : Frac range -> Bool`
[Zulip discussion](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Is.20Infinity.20or.20NaN/near/351162116)

### LINKED ISSUE #5310: Implement builtin for `Num.isNaN : Frac range -> Bool`
[Zulip discussion](https://roc.zulipchat.com/#narrow/stream/231634-beginners/topic/Is.20Infinity.20or.20NaN/near/351162116)

### PR DESCRIPTION
**Pull request by basile-henry**
Closes #5310 and closes #5309

### CODE REVIEW

**Comment by folkertdev** [comment]
do you think you can make them work too for the dev backend (`feature = "gen-dev", run tests with`cargo test-gen-dev`)? fine if not or if it's better to do in a separate PR

**Comment by basile-henry** [comment]
I can have a go at it 👌

**Comment by basile-henry** [comment]
@folkertdev Ok, I have the gen_dev x86 working! I haven't implemented the aarch64 version though.

**Review by folkertdev — APPROVED** [review]
awesome, thank you!

**Comment by basile-henry** [comment]
Ah thanks, I was trying to figure out the commit signing bit :sweat_smile: For next PR! :smile:

**Pull request merged**
