### PR TITLE
Fix: #6261 Removed all the mentions of Num.format

### PR DESCRIPTION
**Pull request by dotslashbit**
Fix: [#6261](https://github.com/roc-lang/roc/issues/6261) Removed all the mentions of Num.format

### CODE REVIEW

**Review by Anton-4 — APPROVED** [review]
Thanks @dotslashbit!

**Comment by Anton-4** [comment]
No big deal, but there's no need to press the update branch button. It's convenient to have the button available but rarely necessary.

**Review by Anton-4 — APPROVED** [review]

**Comment by dotslashbit** [comment]
> No big deal, but there's no need to press the update branch button. It's convenient to have the button available but rarely necessary.

Ok, thank you, looking forward to create more PRs

**Comment by Anton-4** [comment]
Can you merge this @rtfeldman?

**Pull request merged**
