### PR TITLE
move everything in getting_started folder to website

### PR DESCRIPTION
**Pull request by jeffnm**
Addresses #6764 

Key changes

- `install.md` is now in `www/content/install/index.md`
- guides from `getting_started/` are now in `www/content/install/`
- guides' h1 headings were shortened to fit better on the site
- urls were updated within the install/ files

Questions

- I moved the `getting_started/README.md` to `www/content/install/getting_started.md`. It has a lot of overlap with the `install/index.md`. Would it be desirable to combine them somehow? Or is it intended to replace it? I found that it was linked from the Tutorial installation section, so I also updated that link in the meantime.
- I used relative paths with `.html` extensions. Was that ok? Or are we supposed to leave the .html extension off of the URL paths? 
- Any other changes?

### CODE REVIEW

**Comment by jeffnm** [comment]
I've removed the `.html` file extensions from the URLs to and in the getting started pages, per the feedback on Zulip.

**Review by lukewilliamboswell — APPROVED** [review]
This looks good, thank you

**Comment by lukewilliamboswell** [comment]
@jeffnm can you please sign your commits? 

You should be able to use something like `git rebase --exec 'git commit --amend --no-edit -n -S' -i HEAD~4`.

Thank you

**Comment by jeffnm** [comment]
@lukewilliamboswell I hope I signed things properly this time. I don't have a lot of experience signing commits and had to set up a gpg key, but I think it worked.

**Review by lukewilliamboswell — APPROVED** [review]

**Pull request merged**
