### PR TITLE
builtin(str): implement Str.withCapacity

### PR DESCRIPTION
**Pull request by snprajwal**
Provides `Str.withCapacity : Nat -> Str` (see #664)

### CODE REVIEW

**Comment by snprajwal** [comment]
@ayazhafiz PTAL

**Review by ayazhafiz — CHANGES_REQUESTED** [review]
This looks great! Would you mind adding a test to `crates/compiler/test_gen/src/gen_str.rs`?

**Review by ayazhafiz — APPROVED** [review]
Excellent, thank you!

**Comment by snprajwal** [comment]
Oops! Forgot to get rid of the newline

**Review by ayazhafiz — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
