### PR TITLE
Parser package and basic example

### PR DESCRIPTION
**Pull request by lukewilliamboswell**
As discussed at [zulip thread](https://roc.zulipchat.com/#narrow/stream/316715-contributing/topic/Parser.20Package/near/321691505)

### CODE REVIEW

**Comment by lukewilliamboswell** [comment]
I've renamed the basic example and added it to run in CI. Intent is to review this PR and merge, future PR's I would like to add additional examples apps to demonstrate basic parsing functionalities. In future the Parser package will likely be moved into its own repository so that we can have URL's for the release builds.

**Comment by lukewilliamboswell** [comment]
Note that I deleted the zig platform that was in this example folder, and pointed the existing CSV parser example at the rocLovesZig platform as they looked equivalent. @Anton-4 request you review this PR. Thank you.

**Comment by lukewilliamboswell** [comment]
Also I all tests passed for me when I run `cargo test --release -p roc_cli`.

**Comment by Anton-4** [comment]
This should pass once #4929 is merged and pulled into this branch.

**Review by Anton-4 — APPROVED** [review]

**Pull request merged**
