### PR TITLE
close #6723: Update format_files to list all files

### LINKED ISSUE #6723: `roc format --check dir` does not say which file(s) do not conform to the proper roc formatting
```
❯ ./target/release/roc format --check www/content/tutorial-code/
One or more files need to be reformatted.
```

### PR DESCRIPTION
**Pull request by rrrodzilla**
Changed the behavior of the format_files function in the Roc formatter to accumulate and list all files that require reformatting instead of stopping at the first file. This update improves the user experience by providing a comprehensive report of all files that need attention after a format check, allowing for more efficient batch updating of files to conform to formatting standards.

### CODE REVIEW

**Comment by Anton-4** [comment]
Thanks for your contribution @rrrodzilla :)

The failing tests are quite unexpected, an experienced contributor should investigate.

**Comment by rrrodzilla** [comment]
Yeah that's weird. It appears there's a resource issue on GitHub for this wasm32 action. I'm guessing it has something to do with the small temp files being created by the tests which may have pushed it over the edge. I've updated the code to explicitly clean up the temp dirs after use in each test.

**Comment by Anton-4** [comment]
That worked :tada:
Can you allow edits by contributors on this PR @rrrodzilla?
I made some minor stylistic improvements that I'd like to get in.

**Comment by rrrodzilla** [comment]
Oh good. I'm not seeing the normal checkbox to do so. Are you not already able to since you're a participant?

**Comment by rrrodzilla** [comment]
Cool! Apparently edits by contributors [can't be enabled for PRs submitted by organizations](https://github.com/orgs/community/discussions/5634). I've sent you an invite to add to my org's fork so you should be able to make the changes at that point.

**Comment by Anton-4** [comment]
Thanks, I accepted the invite but it appears I still don't have write permission :thinking:

**Comment by rrrodzilla** [comment]
Just updated.

**Comment by Anton-4** [comment]
Success, thanks!

**Comment by Anton-4** [comment]
cli_run::static_site_gen is a flaky failure that started happening in the last 24 hours, it's on main too, I'm investigating it now...

**Comment by rrrodzilla** [comment]
I think the Github Action Runner is hitting it's RAM limit of 16GB. There may be other tests which should be optimized?

**Comment by rrrodzilla** [comment]
Maybe consider printing out the system info during the workflow run:
```yaml
 - name: List disk usage
      run: |
        df -h

    - name: Check available memory
      run: |
        free -h
        ```

**Comment by Anton-4** [comment]
Thanks for the suggestions, disk and ram usage look good during the cli_run::static_site_gen failure.

**Review by Anton-4 — APPROVED** [review]
Thanks @rrrodzilla :)

**Comment by rrrodzilla** [comment]
Curious what the build issue turned out to be?

**Pull request merged**
