### PR TITLE
Reformat the "getting started" guides for clarity & cleanliness

### PR DESCRIPTION
**Pull request by JanCVanB**
- Adhere to [this Markdown style
guide](https://github.com/DavidAnson/markdownlint).
- Simplify & clarify various steps.

### CODE REVIEW

**Review by Anton-4 — APPROVED** [review]
Thanks @JanCVanB :)

**Comment by Anton-4** [comment]
@JanCVanB can you sign commit [2ed14f6](https://github.com/roc-lang/roc/pull/3910/commits/2ed14f6ec3f3083863588f244347fc674a6c4b21)?

**Comment by JanCVanB** [comment]
@Anton-4 Done!

**Comment by JanCVanB** [comment]
@Anton-4 I doubt this PR caused that failure. Wat do?

**Comment by JanCVanB** [comment]
I've manually re-run the failed apple silicon workflow - fingers crossed!

**Review by rtfeldman — APPROVED** [review]

**Pull request merged**
