### PR TITLE
Added the interface modules and Summary sections. Reorganisation and 

### PR DESCRIPTION
**Pull request by P8ace**
…extra notes amended wherever necessary

This is a relatively small commit.

While going through the tutorial, I felt as if the ultimate goal is to have an interactive tutorial with the Roc editor. 
While its great, I would like to see the online tutorials to be complete and gives the learner a sense of where he is in the journey.

I have added a summary section, right before the advanced concepts as delimitation before proceeding futher. 
Hope this is fine.

Would love your feedback.

### CODE REVIEW

**Comment by Anton-4** [comment]
Thanks @P8ace, I've started on the review.

**Comment by P8ace** [comment]
Thanks.
Sensible changes.

**Review by Anton-4 — APPROVED** [review]
Thank you @P8ace, numerous nice improvements!
I've mainly simplified and shortened things in my edit to keep the tutorial easy to understand and prevent it from getting too long.

**Comment by Anton-4** [comment]
btw @rtfeldman will merge this to get around the "The base branch requires all commits to be signed".

**Pull request merged**
