### PR TITLE
Str.splitFirst should not find match if needle is longer than haystack

### LINKED ISSUE #4064: `Str.splitFirst "" "x"` causes `integer subtraction overflowed!` panic
I expect `Str.splitFirst "" "x" == Err NotFound`, but instead I get the following:

```
jan@mackey ~ % roc repl

  The rockin’ roc repl
────────────────────────

Enter an expression, or :help, or :q to quit.

» Str.splitFirst "axb" "x"

Ok { after: "b", before: "a" } : Result { after : Str, before : Str } [NotFound]*

» Str.splitFirst "axb" ""

Ok { after: "axb", before: "" } : Result { after : Str, before : Str } [NotFound]*

» Str.splitFirst "" ""

Ok { after: "", before: "" } : Result { after : Str, before : Str } [NotFound]*

» Str.splitFirst "" "x"
"integer subtraction overflowed!"
thread 'main' panicked at 'Roc hit an error', crates/repl_cli/src/lib.rs:156:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
jan@mackey ~ % 
```

### PR DESCRIPTION
**Pull request by ayazhafiz**
Closes #4064

### CODE REVIEW

**Comment by JanCVanB** [comment]
@ayazhafiz How would you feel, stylistically, about assigning those inline expressions to named variables? I've been reading `matchesAtHelp` for 5 minutes now and I still can't figure out how/why the index walking/comparison math works.

**Comment by ayazhafiz** [comment]
@JanCVanB added some more variables and comments; LMK what you think!

**Comment by JanCVanB** [comment]
Is there any way to do multi-line record destructuring?

This works:
```coffee
    { haystack, haystackIndex, needle, needleIndex, needleLength, endIndex } = state
```
but this doesn't:
```coffee
    {
        haystack,
        haystackIndex,
        needle,
        needleIndex,
        needleLength,
        endIndex,
    } = state
```
because
```
jan@mackey roc % roc check Str.roc 
thread '<unnamed>' panicked at 'internal error: entered unreachable code: Any other pattern should have given a parse error', crates/compiler/can/src/pattern.rs:598:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
^C
```

**Comment by JanCVanB** [comment]
@ayazhafiz What do you think of this refactor?

**Comment by JanCVanB** [comment]
That programmatic formatting, though... I'm almost ready to start a proposal to stop the formatter from enforcing the newline before return values. When applied to sub-expressions and conditional it just makes it confusing.

**Comment by JanCVanB** [comment]
(Is there any performance hit for record-ifying the parameters? I hope not.)

**Review by JanCVanB — APPROVED** [review]

**Comment by JanCVanB** [comment]
If there's no way to multi-line that destructuring, no performance or stylistic problems with my refactor, and no way today to stop the formatter from doing that
look
then I'm ready to merge. Also happy to discuss further!

**Review by JanCVanB — APPROVED** [review]

**Comment by ayazhafiz** [comment]
lgtm! I think we just need the commits to be signed @JanCVanB

**Comment by JanCVanB** [comment]
Whoops! Importing GPG key onto this machine now...

**Comment by JanCVanB** [comment]
Phew, finally. It turns out I've never set up GPG with Git on a mac before - that was a little more complicated than expected.

**Review by JanCVanB — APPROVED** [review]
We're good to go.

**Pull request merged**
