### PR TITLE
Unmacro parser combinators

### PR DESCRIPTION
**Pull request by JackoCoolio**
This PR converts a bunch of the macro parser combinators in `parser.rs` back into regular functions. They were previously converted to macros so that the rust compiler didn't explode, but it's gotten better since then, and I don't run into any issues with compilation. As a bonus, compiling `roc_parse` is now about 1.5s faster on my machine.

See zulip discussion [here](https://roc.zulipchat.com/#narrow/stream/395097-compiler-development/topic/Casual.20Conversation/near/433171171).

### CODE REVIEW

**Comment by JackoCoolio** [comment]
Oops, looks like I forgot to check doctests

**Review by ayazhafiz — DISMISSED** [review]
Great change. Thank you!

**Review by ayazhafiz — APPROVED** [review]

**Comment by ayazhafiz** [comment]
This has conflicts now. @JackoCoolio would you prefer to resolve them or would you like one of us to pick up the conflict resolution?

**Comment by Anton-4** [comment]
So... I've fixed the conflicts but I can't push to JackoCoolio:unmacro_parsers:
```
❯ git push origin unmacro_parsers
Confirm user presence for key ECDSA-SK SHA256:JS8iH+oe4aaJSIc30lcOQg6HcT2Po/HztHBbh9nnEnw
User presence confirmed
Enumerating objects: 49, done.
Counting objects: 100% (49/49), done.
Delta compression using up to 32 threads
Compressing objects: 100% (25/25), done.
Writing objects: 100% (25/25), 6.54 KiB | 3.27 MiB/s, done.
Total 25 (delta 21), reused 0 (delta 0), pack-reused 0 (from 0)
remote: Resolving deltas: 100% (21/21), completed with 11 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/unmacro_parsers.
remote: error: Commits must have verified signatures.
To github.com:JackoCoolio/roc.git
 ! [remote rejected]     unmacro_parsers -> unmacro_parsers (protected branch hook declined)
error: failed to push some refs to 'github.com:JackoCoolio/roc.git'
```
@JackoCoolio do you have some custom settings enabled on your fork?

**Comment by JackoCoolio** [comment]
Hey, sorry for going AWOL on this PR!

@Anton-4 - I set up a rule to require signed commits because I forgot to sign them once and had to rebase, which dismissed Ayaz's review. I removed that rule for now; do you know of a way to do something similar without this happening again?

Anyway, thanks for taking over the conflicts. I'm hoping to start contributing again once stuff at work slows down a little.

**Comment by Anton-4** [comment]
Thanks for removing the rule @JackoCoolio :)

> do you know of a way to do something similar without this happening again?

Enabling commit signing by default on your side could work well enough:
```
$ git config --global user.signingkey YOUR_GPG_KEY_ID
$ git config --global commit.gpgsign true
```

> I'm hoping to start contributing again once stuff at work slows down a little.

No worries :heart:

**Review by Anton-4 — APPROVED** [review]

**Pull request merged**
