### PR TITLE
added-para

### PR DESCRIPTION
**Pull request by KekmaTime**
I have added the paragraph.
Do let me know if there are any changes to be done in it. Thanks!

### CODE REVIEW

**Review by Anton-4 — APPROVED** [review]
Thanks @KekmaTime!

**Comment by Anton-4** [comment]
This PR closes #5603

**Comment by KekmaTime** [comment]
@Anton-4 what is this merging is blocked? (I'm curious)

**Comment by Anton-4** [comment]
We require all our commits to be signed to prevent impersonation, we really only care about main contributors signing their commits but github does not allow that kind of granularity.

Can you merge this @rtfeldman?

**Comment by KekmaTime** [comment]
> (rtfeldman can merge commits that are not signed)

oh okayy

**Pull request merged**
