### PR TITLE
Fixed `roc format --stdin --stdout` to format output

### LINKED ISSUE #6088: `--stdin` flag in `roc format` not behaving correctly
# setup to reproduce
- system - aarch64-darwin (M1 macbook air); macOS 13.4.1
- install the Roc compiler via
    ```sh
    nix shell github:roc-lang/roc/3d8884a96d44e2101ce8932336b74e2b9416e029
    ```
- create a basic roc file with proper Roc syntax but improper formatting, like `test.roc`:
    ```coffeescript
    app "hello"
        packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br" }
        imports [pf.Stdout]
        provides [main] to pf
    



    main = Stdout.line "I'm a Roc application!"
    ```

# working action
```sh
roc format --stdout test.roc
```
produces this in stdout (note the several sequential line returns are reduced to 2):
```coffeescript
app "hello"
    packages { pf: "https://github.com/roc-lang/basic-cli/releases/download/0.5.0/Cufzl36_SnJ4QbOoEmiJ5dIpUxBvdB3NEySvuH82Wio.tar.br" }
    imports [pf.Stdout]
    provides [main] to pf

main = Stdout.line "I'm a Roc application!"
```

# buggy action
IIUC this command *should* produce the same results as described above, but instead passes to stdout the *unformatted* content:
```sh
cat test.roc | roc format --stdin --stdout
```

### PR DESCRIPTION
**Pull request by CrepeGoat**
fixes #6088

### CODE REVIEW

**Review by rtfeldman — DISMISSED** [review]
@CrepeGoat This looks ready to merge to me!

I've approved it, but since it's still in Draft, I wasn't sure if you wanted to make any other changes before merging. 😄

**Comment by CrepeGoat** [comment]
Awesome, thanks!

I have this in draft because I think I technically need an approval from my
company (Google) to make this kind of open-source contribution. I’m not
sure about the legal specifics but I don’t want to have any issues after
merging in to main, and then having to surgically remove it from the repo
because “no that’s our code”. Just trying to be safe out of an abundance of
caution because big tech is big and sometimes scary.

I should get an approval this coming week, I’ll change this to a normal PR
once that happens.

Thanks again!

Crepe

**Comment by CrepeGoat** [comment]
Got the OK -> should be good to merge! Thanks again @rtfeldman  🙂

**Comment by rtfeldman** [comment]
Don't worry about the test failures - something made it into `main` somehow. https://github.com/roc-lang/roc/pull/6117 should fix that, then this will be ready to merge! 🎉

**Review by Anton-4 — APPROVED** [review]

**Pull request merged**
