### PR TITLE
fix `nix-build` on macos

### PR DESCRIPTION
**Pull request by BrianHicks**
also took the opportunity to move a few things into the incoming attrset so they can be overridden when we submit to nixpkgs.

### CODE REVIEW

**Review by Anton-4 — DISMISSED** [review]

**Comment by Anton-4** [comment]
Can you pull in the main branch @BrianHicks? There was an issue because we renamed the branches, that fix is now on main.

**Comment by BrianHicks** [comment]
I rebased, then remembered why that's a bad idea with regards to #3764 😵 

Aaaaanyway that has the fix

**Comment by Anton-4** [comment]
Should we close this PR in favor of #3764 or did I miss anything?

**Comment by BrianHicks** [comment]
oh, hmm, that would be fine. I just made separate PRs since unwanted formatting changes can be annoying. But since we're OK with both going in, no reason to have to test/ merge twice… so yes, let's just do #3764!

**Pull request closed without merging**
