### PR TITLE
enableing more tests on windows

### PR DESCRIPTION
**Pull request by Anton-4**

### CODE REVIEW

**Comment by Anton-4** [comment]
Going to give this a try with a prebuilt windows nightly:
```
roc.exe run .\examples\platform-switching\rocLovesRust.roc
```

**Comment by Anton-4** [comment]
still working on this

**Comment by Anton-4** [comment]
I need to check if the code here is up-to-date with what I had locally, I had to do so many small updates that I stopped doing commits and running through github actions.

**Comment by ayazhafiz** [comment]
@Anton-4 is this PR still relevant?

**Pull request closed without merging**
